### ISSUE TITLE
Setup https certificate

### ISSUE THREAD

**Issue by ogenstad** [netsysops/netsysops.github.io#50]
Setup certificate and "proxy" for GitHub Pages.

**Comment by mirceaulinic** [comment]
If this brings any ease, we could signup this on Cloudflare and have both #50 and #51 solved immediately. Not because it's my employer, but I could probably declare it as my own website and have a BIZ subscription for free.
But, I aware you, this means poor caching.
Let me know if you think that might help at all.

**Comment by ogenstad** [comment]
David was going to setup something at Fastly. Perhaps we can look into Cloudflare if we run into problems with that?

**Comment by dbarrosop** [comment]
Yeah, we can go with one or the other, caching with Fastly is better but there isn't a free tier. I will start poking people next week and if I see it's too much hassle we can go with cloudflare. I don't think caching is a concern anyway.

**Comment by mirceaulinic** [comment]
FYI: Github pages have usage limit: https://help.github.com/articles/what-is-github-pages/#usage-limit. I don't find exactly the whole document (or perhaps they changed the limits), but if I recall correctly there was a limit of about 100k cache-pull requests/month or so. Anyway, we won't reach this limit anytime soon 😆

**Comment by dbarrosop** [comment]
Hahahaha, I don't think those numbers should be a concern either. And if we get to those numbers, given that all the content is static, it would be cached anyway.

**Comment by ogenstad** [comment]
Yeah, I think we're safe for now. :)

**Comment by dbarrosop** [comment]
Sorry for slacking on this one. It's fixed now. I also sent a PR to automatically purge content after a successful build:

https://github.com/netsysops/netsysops.github.io/pull/119

**Comment by ogenstad** [comment]
Perfect, thanks!

No problems regarding the Slacking!
