### ISSUE TITLE
ggabriele image for /contributors/

### ISSUE THREAD

**Issue by ogenstad** [netsysops/netsysops.github.io#9]
Find a 600x400 image for /contributors/ and header.teaser for the page /ggabriele/.

**Comment by ogenstad** [comment]
@GGabriele, do you have an image we can use? I can help you with rescaling and cutting the image if needed.

**Comment by GGabriele** [comment]
Trying to find an HQ image of myself is an harder task than you think

![me](https://cloud.githubusercontent.com/assets/4542862/21586740/9437ba0a-d0d4-11e6-8c30-2950ab2dce96.png)

**Comment by GGabriele** [comment]
@ogenstad here we go 
![me](https://cloud.githubusercontent.com/assets/4542862/21592377/416e2276-d10d-11e6-81c8-af0f1d382caf.png)

**Comment by ogenstad** [comment]
@GGabriele, thanks! I've updated the site with this.
